### ISSUE TITLE
Cannot run docker image

### ISSUE THREAD

**Issue by chaoticthegreat** [AirHockeyChallenge/air_hockey_challenge#10]
I try running the docker image as said in the installation guide and get this message 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/62819056/228087012-8acce706-7f49-48f2-b4a4-31f7c271dccc.png">
and then in just hangs like that. I can't keyboard interrupt, all I can do is just quit the terminal (PowerShell on Windows 11)
I also tried running the docker image on docker desktop in which I get this error
<img width="776" alt="image" src="https://user-images.githubusercontent.com/62819056/228087205-cc2d29a4-d2a0-4431-bbd0-7321a6759a19.png">
The test command works locally, but I can't attempt to run it inside the docker container at all, since it immediately crashes.
Only changes I've made was to install gpu version of torch via their guide and to rename the docker-compose-nvidia.yaml file to docker-compose.yaml. I also skipped the step where it says to install the NVIDIA Container Toolkit because link gives guide on how to do it on Linux and not on windows (or wsl 2).

**Comment by ryanabraham1** [comment]
EDIT: I have (or think) that I have installed the Container Toolkit, but it still gives the same error

**Comment by PuzeLiu** [comment]
Hi, 
Regarding the second error. You need to first implement an agent. For testing purposes, you can put the dummy agent example: 
https://air-hockey-challenges-docs.readthedocs.io/en/latest/framework.html#dummy-agent 
in the `air_hockey_agent/agent_builder.py`

Unfortunately, we can not support the docker installation on windows. You can try to develop the agent locally and evaluate in the docker without visualization. 

In addtion, here is an instruction on the docker usage with windows. Thanks to @amarildolikmeta .
```
Instructions for Docker on Windows:
 
- Install vcxsrv (to let Docker use the display of Windows system for the render)
- Install docker-desktop
- Change docker-compose.yaml like this:
 
--->  replace     DISPLAY=${DISPLAY} 
with          DISPLAY=host.docker.internal:0.0
 
--->  replace     "${PWD}/:/src/2023-challenge"
with          "./:/src/2023-challenge"   
where ./ can be filled with any path inside the docker-container.
 
- Build the image with command docker compose build from Powershell
- Run the container with docker compose run challenge from Powershell
```

**Comment by cube1324** [comment]
I see that our instructions for windows lack some clarity. Docker on windows can be used with either the wsl2 or the Hyper-V backend. We recommend using the wsl2 backend with windows 11. With this setup the following steps work for me:

- Install Docker-Desktop (select wsl2 backend)
- Open a wsl2 shell and navigate to your challenge directory
- `docker compose run challenge` to get an interactive shell in the docker image
- test if rendering works via `python run.py --n_cores 1 -e 3dof-hit --example hit-agent --n_episodes 5 -r`
- test if your own solution works via `python run.py --n_cores 1 -e 3dof-hit -r`

What i assume happened is that you used a Powershell instead of a wsl2 Shell. Thats why it could not find the PWD environment variable and did not copy your code into the docker image. Thus you go the `NotImplementedError`.

Where i cannot help is using nvidia GPU resources from within docker on windows. I have done a lot of research into to this topic and my lastest understanding is that only workstation and server-grade product lines from nvidia (Tesla, Quadro, etc.) provide this feature. Atlest i get an ominous `nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown` error on my 3070. More info on this topic can be found [here](https://community.opendronemap.org/t/gpu-not-used-in-windows/12211/3). If you find a way please let me know but at the moment the only way to use nvidia GPUs in docker is on Linux to my knowledge. 

Also, keep in mind that we do not provide a GPU on the evaluation server. Your solution should be fast enough to fullfill the time constraints with 4 CPU cores. And for training, you do not need to use a docker image.

**Comment by ryanabraham1** [comment]
So, I've been following the steps again, and I installed the docker container on wsl 2 but when I try to run the test command in wsl 2 (not on docker) I get this error.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/62819056/228396347-6715a759-0188-4f50-8e47-4138992d20a9.png">
When I try checking my glx version with glxinfo I get this error
![image](https://user-images.githubusercontent.com/62819056/228396391-80fe996c-79a7-41ec-afae-d5341dd88025.png)
I have looked far and wide for an answer for this but have found nothing useful.
Nvidia-Smi works, and I xeyes (graphical test command) works using Xming (basically a server to display linux graphics)

**Comment by cube1324** [comment]
Thats strange. What is you Windows Version? According to Microsoft Windows 10 Build 19044+ and Windows 11 should support running Linux GUI application (X11 and Wayland) out of the box with wsl2 ([source](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)). You should not install Xming on your own.

One issue could be that your GPU driver is not up to date.  If `xeyes` or `glxgears` still fail with the latest GPU driver you can create a wsl [issue](https://github.com/Microsoft/WSL/issues) for your hardware.

Another participant shared this setup to get the GUI output of docker on windows.  Thanks to @amarildolikmeta.
```
Instructions for Docker on Windows:
 
- Install vcxsrv (to let Docker use the display of Windows system for the render)
- Install docker-desktop
- Change docker-compose.yaml like this:
 
--->  replace     DISPLAY=${DISPLAY} 
with          DISPLAY=host.docker.internal:0.0
 
--->  replace     "${PWD}/:/src/2023-challenge"
with          "./:/src/2023-challenge"   
where ./ can be filled with any path inside the docker-container.
 
- Build the image with command docker compose build from Powershell
- Run the container with docker compose run challenge from Powershell
```
I have not tested this but it might be an option for you.

**Comment by ryanabraham1** [comment]
So `xeyes` works completely fine its just `glxgears` and `glxinfo` that gives me weird errors. They were working at some point, but I think I may have upgraded some kind of package (attempting to get them to upgrade to 1.3) and they just broke after that. I'm not running any weird hardware (3060, i9-11900k) and my drivers are up to date. I'll definetly check out how to get GUI output of docker onto windows, but is there any point  if the test command doesn't.

**Comment by cube1324** [comment]
Okay, whats is the mesa version of your wsl2 distro? You can get it with ` glxinfo | grep 'Mesa'`. I remeber i had a similar issue to you and had to update mesa to resolve it.  You can update your Mesa driver via
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt upgrade
```
More info for upgrading mesa is [here](https://itsfoss.com/install-mesa-ubuntu/).
I don't know if @amarildolikmeta solution will work with your current issues, i honestly would be suprised if it does. A workarround would be to develop your agent on a local windows environment and just build the docker images for submission. This way you dont need to render the simulator from within the docker image.

**Comment by ChaoticChaosTheGreat** [comment]
So I don't know if you saw  but `xeyes` does work (sorry for not highlighting earlier) and I am on my gpus latest driver (3060). I''m also on the latest windows 11 update.

**Comment by ryanabraham1** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/62819056/228696367-d6589c8a-e878-4e37-a9ba-d914cbd56ea1.png">
One of the main problems I'm having is running `glxinfo`. I was trying about a month back to get some rl environments to work specifically the gym-super-mario-bros and it kept on throwing errors about opengl versions. I ended up try just running a few upgrade commands and then it just broke glxinfo completly. So anytime i run glxinfo I get the same error so grepping anything doesn't work. I appreciate you dealing with me but I have been trying to solve this forever

**Comment by ryanabraham1** [comment]
I also did run the commands you suggested but they take no effect. I do have mesa-utils installed and everything and like I said I'm not running weird hardware or anything.

**Comment by cube1324** [comment]
It seems that your have a broken setup in the wsl. I would suggest to reinstall it in a clean way if possible. 
However, you could still develop your agent in Windows and evaluate your solution in docker without visualization. 
The evaluator in the cloud server will not use visualization as well.

**Comment by ryanabraham1** [comment]
Ok, should I delete Ubuntu as well or just WSL?

**Comment by cube1324** [comment]
It should be enough to just reset Ubuntu. This [article](https://pureinfotech.com/reset-wsl-linux-distro-windows-11/) outlines how to reset a wsl distro without deleting and reinstalling it.

**Comment by ryanabraham1** [comment]
Completely unrelated question (bored while everything is installing again) what do you think is a good book or course for reinforcement learning such as this. I don't plan on winning any award or anything at this competition but I thought it would be a good way to learn a bit more.

**Comment by ryanabraham1** [comment]
> It should be enough to just reset Ubuntu. This [article](https://pureinfotech.com/reset-wsl-linux-distro-windows-11/) outlines how to reset a wsl distro without deleting and reinstalling it.

Ok I just reinstalled and it still gives me the same exact error

**Comment by ryanabraham1** [comment]
I think I will try just running local, thank you for trying to help.
