### ISSUE TITLE
Action dimensions for interpolation order 1 and 2

### ISSUE THREAD

**Issue by Thifhi** [AirHockeyChallenge/air_hockey_challenge#22]
The action shape per agent is (1, n_joints) for the interpolation orders 1 and 2, but the _interpolate_trajectory method still expects `action.ndim == 1` which throws an exception as a result. I think you should change them to `action.shape[0] == 1` like the rest.

**Comment by PuzeLiu** [comment]
Hi, Thanks for pointing this out. I think now the bug should be fixed. For interpolation orders 1 and 2, you should send the position command directly with the shape (n_joints,)
